/**
 * Converts a single digit (0-9) to a corresponding uppercase letter (A-J).
 * @param {number | string} digit The digit to convert.
 * @returns {string} The corresponding character.
 */
function digitToChar(digit) {
    return String.fromCharCode('A'.charCodeAt(0) + parseInt(digit, 10));
}

/**
 * Generates a unique alphabetic string based on the current date and time in IST (Indian Standard Time).
 * The string is generated by mapping each digit of the timestamp (YYYYMMDDHHMMSS)
 * to a corresponding letter (0=A, 1=B, ..., 9=J).
 * Timezone information is not included in the output string.
 * @returns {string} A unique, uppercase alphabetic string based on IST.
 */
function generateUniqueAlphabeticString() {
    // Create a new Date object representing the current time in IST (UTC+05:30)
    const now = new Date(new Date().toLocaleString('en-US', { timeZone: 'Asia/Kolkata' }));

    // Helper to pad numbers to two digits
    const pad = (num) => num.toString().padStart(2, '0');

    // Create the full numeric date-time string from the IST date
    const year = now.getFullYear().toString();
    const month = pad(now.getMonth() + 1);
    const day = pad(now.getDate());
    const hour = pad(now.getHours());
    const minute = pad(now.getMinutes());
    const second = pad(now.getSeconds());
    const dateTimeString = `${year}${month}${day}${hour}${minute}${second}`;

    // Convert the numeric date-time string to an alphabetic string
    let dateTimePart = '';
    for (const char of dateTimeString) {
        dateTimePart += digitToChar(char);
    }

    return dateTimePart;
}

// To make the function available for import in other files (e.g., using Node.js modules)
if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
    module.exports = { generateUniqueAlphabeticString };
}
